package rules;
import com.itegra.auditcom.domain.AlimentoAcordanteEntrada;
import com.itegra.auditcom.domain.ResultadoAlimentoAcordanteEntrada;
dialect  "mvel"

rule "Definir Carga Liquida Base 1"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "7%_CESTA_BASICA" && regiaoEmitente == "INTERNO" )
	then
		resultado.setPercentualCargaLiquida( 0.02 );
end

rule "Definir Carga Liquida Base 2"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "7%_CESTA_BASICA" && regiaoEmitente == "SUL_SUDESTE" )
	then
		resultado.setPercentualCargaLiquida( 0.045 );
end

rule "Definir Carga Liquida Base 3"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "7%_CESTA_BASICA" && regiaoEmitente == "OUTROS" )
	then
		resultado.setPercentualCargaLiquida( 0.035 );
end

rule "Definir Carga Liquida Base 4"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "12%_CESTA_BASICA" && regiaoEmitente == "INTERNO" )
	then
		resultado.setPercentualCargaLiquida( 0.026 );
end

rule "Definir Carga Liquida Base 5"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "12%_CESTA_BASICA" && regiaoEmitente == "SUL_SUDESTE" )
	then
		resultado.setPercentualCargaLiquida( 0.056 );
end

rule "Definir Carga Liquida Base 6"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "12%_CESTA_BASICA" && regiaoEmitente == "OUTROS" )
	then
		resultado.setPercentualCargaLiquida( 0.044 );
end

rule "Definir Carga Liquida Base 7"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "17%" && regiaoEmitente == "INTERNO" )
	then
		resultado.setPercentualCargaLiquida( 0.03 );
end

rule "Definir Carga Liquida Base 8"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "17%" && regiaoEmitente == "SUL_SUDESTE" )
	then
		resultado.setPercentualCargaLiquida( 0.076 );
end

rule "Definir Carga Liquida Base 9"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "17%" && regiaoEmitente == "OUTROS" )
	then
		resultado.setPercentualCargaLiquida( 0.06 );
end

rule "Definir Carga Liquida Base 10"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "25%_VINHOS_SIDRAS_BEBIDASQUENTES" && regiaoEmitente == "INTERNO" )
	then
		resultado.setPercentualCargaLiquida( 0.056 );
end

rule "Definir Carga Liquida Base 11"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "25%_VINHOS_SIDRAS_BEBIDASQUENTES" && regiaoEmitente == "SUL_SUDESTE" )
	then
		resultado.setPercentualCargaLiquida( 0.1620 );
end

rule "Definir Carga Liquida Base 12"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( tipoProduto == "25%_VINHOS_SIDRAS_BEBIDASQUENTES" && regiaoEmitente == "OUTROS" )
	then
		resultado.setPercentualCargaLiquida( 0.1325 );
end
