package rules;
import com.itegra.auditcom.domain.AlimentoAcordanteEntrada;
import com.itegra.auditcom.domain.ResultadoAlimentoAcordanteEntrada;
dialect "mvel"

rule "Definir Carga Liquida Base 1"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2004" && ufEmitente == "CE" )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.02 );
end

rule "Definir Carga Liquida Base 2"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2004" && ufEmitente in ( "SP", "MG", "RJ", "PR", "SC", "RS" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.045 );
end

rule "Definir Carga Liquida Base 3"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2004" && ufEmitente in ( "AC", "AL", "AP", "AM", "BA", "DF", "ES", "GO", "MA", "MS", "MT", "PA", "PB", "PE", "PI", "RN", "RO", "RR", "SE", "TO" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.035 );
end

rule "Definir Carga Liquida Base 4"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2005" && ufEmitente == "CE" )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.026 );
end

rule "Definir Carga Liquida Base 5"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2005" && ufEmitente in ( "SP", "MG", "RJ", "PR", "SC", "RS" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.056 );
end

rule "Definir Carga Liquida Base 6"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2005" && ufEmitente in ( "AC", "AL", "AP", "AM", "BA", "DF", "ES", "GO", "MA", "MS", "MT", "PA", "PB", "PE", "PI", "RN", "RO", "RR", "SE", "TO" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.044 );
end

rule "Definir Carga Liquida Base 7"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2001" && ufEmitente == "CE" )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.03 );
end

rule "Definir Carga Liquida Base 8"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2001" && ufEmitente in ( "SP", "MG", "RJ", "PR", "SC", "RS" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.076 );
end

rule "Definir Carga Liquida Base 9"
	when
		obj : AlimentoAcordanteEntrada( categoria == "2001" && ufEmitente in ( "AC", "AL", "AP", "AM", "BA", "DF", "ES", "GO", "MA", "MS", "MT", "PA", "PB", "PE", "PI", "RN", "RO", "RR", "SE", "TO" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.06 );
end

rule "Definir Carga Liquida Base 10"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( )
		obj : AlimentoAcordanteEntrada(  ufEmitente == "CE" && (categoria == "2002" || categoria.substring(0,2) == "24"))
	then
		resultado.setPercentualCargaLiquida( 0.056 );
end

rule "Definir Carga Liquida Base 11"
	when
		obj : AlimentoAcordanteEntrada( (categoria == "2002" || categoria.substring(0,2) == "24") && ufEmitente in ( "SP", "MG", "RJ", "PR", "SC", "RS" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.1620 );
end

rule "Definir Carga Liquida Base 12"
	when
		obj : AlimentoAcordanteEntrada( (categoria == "2002" || categoria.substring(0,2) == "24") && ufEmitente in ( "AC", "AL", "AP", "AM", "BA", "DF", "ES", "GO", "MA", "MS", "MT", "PA", "PB", "PE", "PI", "RN", "RO", "RR", "SE", "TO" ) )
		resultado : ResultadoAlimentoAcordanteEntrada( )
	then
		resultado.setPercentualCargaLiquida( 0.1325 );
end