package rules;
import com.itegra.auditcom.domain.AlimentoAcordanteEntrada;
import com.itegra.auditcom.domain.ResultadoAlimentoAcordanteEntrada;
dialect  "mvel"

rule "Acrescentar Carga Liquida Simples Nacional 1"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( simplesNacional == true && regiaoEmitente == "INTERNO" )
	then
		resultado.setPercentualCargaLiquida( getPercentualCargaLiquida()*1.03 );
end

rule "Acrescentar Carga Liquida Simples Nacional 2"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( simplesNacional == true && regiaoEmitente == "SUL_SUDESTE" )
	then
		resultado.setPercentualCargaLiquida( getPercentualCargaLiquida()*1.04 );
end

rule "Acrescentar Carga Liquida Simples Nacional 3"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( simplesNacional == true && regiaoEmitente == "OUTROS" )
	then
		resultado.setPercentualCargaLiquida( getPercentualCargaLiquida()*1.06 );
end

