package rules;
import com.itegra.auditcom.domain.AlimentoAcordanteEntrada;
import com.itegra.auditcom.domain.ResultadoAlimentoAcordanteEntrada;
dialect  "mvel"

rule "regra calcular imposto"
	when
		resultado : ResultadoAlimentoAcordanteEntrada( )
		obj : AlimentoAcordanteEntrada(resultado.isCalcularImposto(  ) == true)
	then		
		resultado.valorImposto = resultado.valorBaseDeCalculo * resultado.percentualCargaLiquida

end